# Generated by Django 5.2.17 on 2026-09-18 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('guidance', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('SHORT_TEXT', 'نص قصير'), ('LONG_TEXT', 'نص طويل'), ('NUMBER', 'عدد'), ('DATE', 'تاريخ'), ('BOOLEAN', 'نعم/لا'), ('SINGLE_SELECT', 'اختيار واحد'), ('MULTI_SELECT', 'اختيار متعدد')], max_length=24)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('help_text', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('COMPLETED', 'مكتملة')], default='DRAFT', max_length=16)),
                ('general_observations', models.TextField(blank=True)),
                ('general_recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(max_length=255)),
                ('description_snapshot', models.TextField(blank=True)),
                ('sort_order_snapshot', models.PositiveIntegerField(default=0)),
                ('local_addition', models.BooleanField(default=False)),
                ('additional_observations', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_nodes', to='core.inspection')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.inspectionnode')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('UNCHECKED', 'غير مفحوص'), ('NOT_APPLICABLE', 'غير معني'), ('COMPLIANT', 'مطابق'), ('OBSERVATION', 'ملاحظة'), ('NON_COMPLIANT', 'غير مطابق')], default='UNCHECKED', max_length=24)),
                ('observation', models.TextField(blank=True)),
                ('local_addition', models.BooleanField(default=False)),
                ('sort_order_snapshot', models.PositiveIntegerField(default=0)),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.checklistitem')),
                ('inspection_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_results', to='core.inspectionnode')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(blank=True, max_length=120)),
                ('commune', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('VERIFIED', 'معتمدة')], default='VERIFIED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='core.institution'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='master_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='core.masterversion'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('INSPECTOR', 'Inspector')], default='INSPECTOR', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('INSTITUTION', 'مؤسسة'), ('NODE', 'عنصر هيكلي'), ('SPECIFICATION', 'مواصفة'), ('ITEM', 'بند')], max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('MERGED', 'مدمج')], default='PENDING', max_length=16)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_resolved', to=settings.AUTH_USER_MODEL)),
                ('source_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='core.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(max_length=255)),
                ('field_type_snapshot', models.CharField(choices=[('SHORT_TEXT', 'نص قصير'), ('LONG_TEXT', 'نص طويل'), ('NUMBER', 'عدد'), ('DATE', 'تاريخ'), ('BOOLEAN', 'نعم/لا'), ('SINGLE_SELECT', 'اختيار واحد'), ('MULTI_SELECT', 'اختيار متعدد')], max_length=24)),
                ('value', models.JSONField(blank=True, null=True)),
                ('local_addition', models.BooleanField(default=False)),
                ('sort_order_snapshot', models.PositiveIntegerField(default=0)),
                ('inspection_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_values', to='core.inspectionnode')),
                ('source_specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.specificationdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='StructureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('inspectable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('master_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.masterversion')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.structurenode')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='specificationdefinition',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='core.structurenode'),
        ),
        migrations.AddField(
            model_name='inspectionnode',
            name='source_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.structurenode'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.structurenode'),
        ),
    ]
